In [1]:
import numpy as np
import pandas as pd
from datetime import datetime

In [2]:
now= datetime.now()
today = now.strftime('%Y-%m-%d')
print(today)

2019-10-21

In [3]:
train_data_01 = pd.read_csv('./player_data/KFA_MU-15_20190913_TR_AM.csv', index_col=['name'])
train_data_02 = pd.read_csv('./player_data/KFA_MU-15_20190914_TR_PM.csv', index_col=['name'])

In [4]:
train_data_01.head()

,position,weight,rpe,play_time(min),total_distance(m),distance_per_minute(m),hsr_distance(m),zone3(m),zone4(m),zone5(m),max_speed(km/h)
name,,,,,,,,,,,
player01,DF,57.2,6,117,7027.2,60.1,108.9,505.6,108.2,0.7,25.2
player02,DF,54.5,7,117,7404.8,63.3,140.9,516.8,133.8,7.1,27.5
player03,DF,61.1,8,117,6980.0,59.7,169.4,427.5,149.1,20.3,28.7
player04,DF,59.7,9,117,7537.4,64.4,268.4,676.0,233.4,35.0,27.7
player05,DF,66.0,6,117,7047.2,60.2,159.9,389.2,140.7,19.2,27.5

In [5]:
train_data_02.tail()

,position,weight,rpe,play_time(min),total_distance(m),distance_per_minute(m),hsr_distance(m),zone3(m),zone4(m),zone5(m),max_speed(km/h)
name,,,,,,,,,,,
player15,GK,54.0,5,82,3591.1,43.8,1.0,92.1,1.0,0,20.6
player17,GK,53.3,7,82,3205.6,39.1,0.0,140.8,0.0,0,19.2
player19,GK,52.0,9,82,3321.5,40.5,0.6,92.7,0.6,0,20.0
player21,FW,63.9,4,82,4026.0,49.1,11.0,147.8,11.0,0,22.0
player23,FW,54.1,2,82,4630.9,56.5,4.2,348.6,4.2,0,21.2

In [6]:
train_data_01.info()

<class 'pandas.core.frame.DataFrame'>
Index: 23 entries, player01 to player23
Data columns (total 11 columns):
position                  23 non-null object
weight                    23 non-null float64
rpe                       23 non-null int64
play_time(min)            23 non-null int64
total_distance(m)         23 non-null float64
distance_per_minute(m)    23 non-null float64
hsr_distance(m)           23 non-null float64
zone3(m)                  23 non-null float64
zone4(m)                  23 non-null float64
zone5(m)                  23 non-null float64
max_speed(km/h)           23 non-null float64
dtypes: float64(8), int64(2), object(1)
memory usage: 2.2+ KB

In [7]:
train_data_02.info()

<class 'pandas.core.frame.DataFrame'>
Index: 19 entries, player01 to player23
Data columns (total 11 columns):
position                  19 non-null object
weight                    19 non-null float64
rpe                       19 non-null int64
play_time(min)            19 non-null int64
total_distance(m)         19 non-null float64
distance_per_minute(m)    19 non-null float64
hsr_distance(m)           19 non-null float64
zone3(m)                  19 non-null float64
zone4(m)                  19 non-null float64
zone5(m)                  19 non-null int64
max_speed(km/h)           19 non-null float64
dtypes: float64(7), int64(3), object(1)
memory usage: 1.8+ KB

In [8]:
train_data_01.index

Index(['player01', 'player02', 'player03', 'player04', 'player05', 'player06',
       'player07', 'player08', 'player09', 'player10', 'player11', 'player12',
       'player13', 'player14', 'player15', 'player16', 'player17', 'player18',
       'player19', 'player20', 'player21', 'player22', 'player23'],
      dtype='object', name='name')

In [9]:
for player in train_data_01.index:
    player_path = './total_data/'+player+'.csv'
    player_data = train_data_01.loc[player:player].rename(index={player:today})
    player_data.to_csv(player_path, mode='a', header=False)

In [10]:
for player in train_data_02.index:
    player_path = './total_data/'+player+'.csv'
    player_data = train_data_02.loc[player:player].rename(index={player:today})
    player_data.to_csv(player_path, mode='a', header=False)